name = "SmoothingSplines"
uuid = "102930c3-cf33-599f-b3b1-9a29a5acab30"
authors = ["Nikos Ignatiadis <nikos.ignatiadis01@gmail.com>"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Reexport = "0.2"
StatsBase = "0.33"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
